name: 'TODO Finder Action'

description: 'Find and comment on TODOs in pull requests'

inputs:
  token:
    description: 'GitHub token'
    required: true
  exclude:
    description:
      'Exclude file patterns. User list of globs separated by new line.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
